version: '3'
services:
  app:
    build: .
    container_name: 'medical-clinic-app'
    depends_on:
      - 'postgres-db'
      - 'logstash'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/medical-db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
    ports:
      - '8080:8080'

  visit-gateway-app:
    build: ../../visit-gateway
    container_name: 'visit-gateway-app'
    ports:
      - '8081:8081'
    environment:
      - MEDICAL_CLINIC_URL=http://app:8080
    depends_on:
      - app
      - postgres-db

  postgres-db:
    image: postgres
    container_name: 'postgres'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'medical-db'
    ports:
      - '5432:5432'
    volumes:
      - medical-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - '5051:80'
    depends_on:
      - postgres-db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=elastic_password
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic_username
      - ELASTICSEARCH_PASSWORD=elastic_password
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.0
    container_name: logstash
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./logstash/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro,Z
      - ./logstash/config/jvm.options:/usr/share/logstash/config/jvm.options:ro,Z
    ports:
      - "5050:5050"
    depends_on:
      - elasticsearch

volumes:
  medical-data:
  pgadmin-data:
  elasticsearch-data: